# -*- coding: utf-8 -*-
"""A5_huggingfaceB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MeFJsPCiroeeA3hqzOlB4RlEeJjQputJ
"""

## 새주석: PIP
!pip install transformers

## 새주석: transformer 버전확인
import transformers

print(transformers.__version__)

## 새주석: pipeline 생성
from transformers import pipeline

senti = pipeline('sentiment-analysis')

senti.model

## 새주석: 책 '어린왕자'에서의 문장

words1 = "All grown-ups were once children… only a few of them remember it"

words2 = """No one has tamed you and you haven’t tamed anyone.
You’re the way my fox was.
He was just a fox like a hundred thousand others.
But I’ve made him my friend, and now he’s the only fox in the world."""
words3 = "What does tamed mean? It’s something that’s been too often neglected. It means to create ties."

print(senti([words1, words2, words3]))

## 새주석: 책 '꽃들에게 희망을'에서의 문장

words = "They have to want to learn to fly so much that you are willing to give up being a caterpillar."

print(senti([words]))

## 새주석: 책 '선과 모터사이클 관리술'에서의 문장

words = 'The truth knocks on the door and you say, "Go away, I\'m looking for the truth," and so it goes away. Puzzling.'

print(senti([words]))